### ISSUE TITLE
Ignore instead of throwing "out-of-bound numeric index"

### ISSUE THREAD

**Issue by fukaraadam** [bellard/quickjs#200] opened 2023-11-27 16:13 UTC
In Node.js and browser environments, following code error just ignored, but QuickJS throws error:

```javascript
  const out = new Uint8Array(2);
  out[0]= 10;
  out[1] = 11;
  // Below this will throw error for QuickJS and ignored for other environments
  out[2] = 12;
  console.log("out: ", out);  // [10, 11]
```

Found out this while trying to use a npm package. I believe behaving in similar way with other environments would make it easier to use general packages in QuickJS. At least, error message can describe how to optionally disable this type of error.

**Comment by dchest** [comment] 2023-11-28 08:11
I cannot reproduce this. What flags/additional libraries do you use?

**Comment by saghul** [comment] 2023-11-28 08:26
I cannot reproduce it either.

**Comment by saghul** [comment] 2023-11-28 14:15
I can reproduce it now, and it is intentional, based on the code. I guess we'd need to check the ECMA spec.

**Comment by bellard** [comment] 2023-12-09 12:12
It should be fixed now.

**Closed by bellard** 2023-12-09 12:12 UTC
